buyer:
  code: autoeuro_ru
  name: Авто-Евро
  enabled: true
  aliases:
    domains:
    - '@autoeuro.ru'
    senders:
    - order@autoeuro.ru
    - claim@autoeuro.ru
    - reclamations.supplier@autoeuro.ru
    subject_contains:
    - запрос на снятие
    - отказ клиента
    - Авто-Евро
    - Запрос на возврат товара
    - Возврат товара
    body_contains:
    - ws.autoeuro.ru
    - снять этот товар
    - не поставлять его к нам
    - Поступил запрос от клиента на возврат товара
    - товар находится на нашем складе и готов к выдаче
    - организовать забор возврата
    - Тип рекламации
    - Приходный документ
    - 'Причина: Отказ конечного покупателя'
statuses:
  quality_refusal:
  - отказ клиента
  - отказ от клиента
  - запрос на снятие
  - снять этот товар
  - не поставлять его к нам
  - Новый товар надлежащего качества
  - Отказ конечного покупателя
  - готов к выдаче
fields:
  regex:
    document_number:
    - Подтверждение\s*№\s*([A-ZА-Я0-9\-/]+)
    - Приходный\s+документ:\s*№?\s*([0-9]+)
    - Документ\s+Название\s+Бренд\s+Артикул\s+Кол-во\s+Цена\s+C?т-ть\s+№\s*([0-9]+)
    - (?:(?:№|#)\s*)\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    - (?:(?:УПД|накладн[аяой]+|документ[еу]?|счёт-фактур[аеу]?|заказ[еу]?|счёт|реализаци[яею]+)\s*(?:№|#)?\s*)\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=[А-ЯЁа-яё])'
    part_number:
    - Код\s*[:#-]\s*([A-Z0-9][A-Z0-9._\/-]{3,40})
    - Товар:\s*[A-ZА-ЯЁ0-9._/-]+\s*/\s*([A-Z0-9._/-]+)\s*/
    - MASTERKIT\s*/\s*([A-ZА-Я0-9][A-ZА-Яa-zA-Z0-9._\-/]{1,40})
    - SAKURA\s*/\s*([A-ZА-Я0-9][A-ZА-Яa-zA-Z0-9._\-/]{1,40})
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{3,28})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{2,27})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{5,30})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{4,29})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{6,31})(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])'
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{7,32})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{8,33})(?=[А-ЯЁа-яё])
    - Товар\s*:\s*([A-ZА-Я0-9][A-ZА-Яa-zA-Z0-9._\-/]{1,40})
    - гранный\s*\(\s*([A-ZА-Я0-9][A-ZА-Яa-zA-Z0-9._\-/]{1,40})
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,23})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=[А-ЯЁа-яё])
    brand:
    - Производитель\s*[:#-]\s*([^\n\r]+)
    - Товар:\s*([A-ZА-ЯЁ0-9._/-]+)\s*/\s*[A-Z0-9._/-]+\s*/
    - Товар\s*:\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{2,27})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,23})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=[А-ЯЁа-яё])
    - (ROCK\ FORCE)(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])
    - (JP\ GROUP)(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{6,31})(?=[А-ЯЁа-яё])
    - (MAGNETI\ MARELLI)(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,24})(?=[А-ЯЁа-яё])
    product_name:
    - Наименование\s*[:#-]\s*([^\n\r]+)
    - Товар:\s*[A-ZА-ЯЁ0-9._/-]+\s*/\s*[A-Z0-9._/-]+\s*/\s*([^\n\r]+)
    - 77IC010\s*/\s*([^\n\r]{3,80})
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{19,44}?)(?=[А-ЯЁа-яё])
    - (Колодки\ audi\ a3/vw\ golf\ v,touran\ 2003=>)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{33,58}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{13,38}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{45,70}?)(?=\d)
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{15,40}?)(?=[А-ЯЁа-яё])
    - (Фильтр\ топл\.mb\ w222\ 3\.0d)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{17,42}?)(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{28,53}?)(?=\d)'
    - (Диск\ торм\.kia\ sportage\ 2\.0,\ 2\.7/\ hyundai\ ix35\ 2\.0\ 2004\ \->)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{32,57}?)(?=[А-ЯЁа-яё])
    - (Колодки\ тормозные\ передние\ sp1595in)(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)(?=\d)'
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{34,59}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{36,61}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{10,35}?)(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{7,32}?)(?=[А-ЯЁа-яё])'
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{16,41}?)(?=[A-Za-z])'
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)'
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{25,50}?)'
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{24,49}?)(?=[А-ЯЁа-яё])'
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[А-ЯЁа-яё])
    - (Опора\ двигателя\ прав\.ford\ mondeo\ ca2\ 2007\-2014\ fdm\-ca2rh)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{12,37}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{31,56}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{45,70}?)(?=[А-ЯЁа-яё])
    - (Вороток\ 3/4\ l=330мм\ г\-образный\ rock\ force)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{48,73}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{30,55}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{12,37}?)(?=\d)
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{41,66}?)(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*(Масло\ моторное\ 900\ SXR\ 5W\-40)(?=\d)'
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{11,36}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{4,29}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{53,78}?)(?=[А-ЯЁа-яё])
    - (Колодки\ пер\.mercedes\ w210,w211)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{25,50}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{39,64}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{8,33}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{37,62}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{67,92}?)(?=[А-ЯЁа-яё])
    quantity:
    - Количество\s*[:#-]\s*(\d+(?:[,.]\d+)?)
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})(?=[А-ЯЁа-яё])
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})(?=\d)
    - '[A-Za-z]+([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})'
    price:
    - Цена\s*[:#-]\s*([0-9]+(?:[,.][0-9]{2})?)
    document_date:
    - Дата\s+поставки\s*[:#-]\s*([0-9]{4}-[0-9]{2}-[0-9]{2})
    - Приходный\s+документ:\s*№?\s*[0-9]+\s+от\s+([0-9]{1,2}[.\-/][0-9]{1,2}[.\-/][0-9]{2,4})
    - Документ\s+Название\s+Бренд\s+Артикул\s+Кол-во\s+Цена\s+C?т-ть\s+№\s*[0-9]+\s+от\s+([0-9]{1,2}[.\-/][0-9]{1,2}[.\-/][0-9]{2,4})
    comment:
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{38,63}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{34,59}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{19,44}?)(?=[А-ЯЁа-яё])
    - (?:(?:причина\s+(?:клиента|возврата|обращения|брака|претензии)?|комментарий|описание|неисправность|дефект)[:\s\-]*)\s*([^\n\r]{4,160})
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{21,46}?)(?=[А-ЯЁа-яё])'
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{36,61}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{8,33}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[А-ЯЁа-яё])
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{30,55}?)(?=[А-ЯЁа-яё])
required_documents:
- подтверждение заказа
- акт возврата при фактической поставке
field_extractors: []
processing_types:
  pre_delivery_cancellation:
  - запрос на снятие
  - снять этот товар
  - не поставлять его к нам
  follow_up_request:
  - что по запросу
  - ожидаем решение
  return_ready_notification:
  - товар находится на нашем складе и готов к выдаче
  - готов к выдаче
  - организовать забор возврата
