buyer:
  code: avtoformula
  name: Автоформула
  enabled: true
  aliases:
    domains:
    - '@avtoformula.ru'
    senders: []
    folders: []
    subject_contains:
    - ТОРГ-2
    - акт
    - недопоставка
    - Запрос на возврат товара надлежащего качества
    body_contains:
    - недостача
    - накладной
    - акт ТОРГ-2
    - товар надлежащего качества
    - отказа конечного покупателя
statuses:
  shortage:
  - недостача
  - недопоставка
  - обнаружена недостача
  quality_refusal:
  - товар надлежащего качества
  - отказ конечного покупателя
  defect:
  - несоответствие
  - обнаружено несоответствие
processing_types:
  new_return:
  - акт ТОРГ-2
  - недостача
  - товар надлежащего качества
  - запрос на возврат товара надлежащего качества
fields:
  regex:
    document_number:
    - накладн[ао]й\s*№\s*([0-9]+)
    - по\s+документу\s*№\s*([0-9]{4,})
    - (?:(?:УПД|накладн[аяой]+|документ[еу]?|счёт-фактур[аеу]?|заказ[еу]?|счёт|реализаци[яею]+)\s*(?:№|#)?\s*)\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    document_date:
    - накладн[ао]й\s*№\s*[0-9]+\s*от\s*([0-9]{1,2}[.\-/][0-9]{1,2}[.\-/][0-9]{2,4})
    - по\s+документу\s*№\s*[0-9]{4,}\s+от\s+([0-9]{1,2}[.\-/][0-9]{1,2}[.\-/][0-9]{2,4})
    part_number:
    - По\s+товару\s+([A-Z0-9][A-Z0-9._\/-]{3,40})
    - качества\s+по\s+причине\s+отказа\s+конечного\s+покупателя\s+([A-Z0-9][A-Z0-9._\/-]{3,40})
    - ^\s*([A-Z0-9][A-Z0-9._\/-]{3,40})\s+[A-ZА-ЯЁа-яё0-9._\/-]+\s+.+?\s+в\s+количестве
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{2,27})(?=[A-Za-z])'
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[A-Za-z])'
    quantity:
    - количестве\s+(\d+(?:[,.]\d+)?)\s*шт
    brand:
    - '[A-Za-z]+(ROCK\ FORCE)(?=[А-ЯЁа-яё])'
    - '[A-Za-z]+([A-Za-z0-9][A-Za-z0-9._/\-]{1,23})(?=[А-ЯЁа-яё])'
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])
    product_name:
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{23,48}?)(?=[А-ЯЁа-яё])'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{39,64}?)'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{16,41}?)'
    comment:
    - (?:(?:причина\s+(?:клиента|возврата|обращения|брака|претензии)?|комментарий|описание|неисправность|дефект)[:\s\-]*)\s*([^\n\r]{4,160})
    - день\s*!\s*([^\n\r]{4,160})
required_documents:
- акт ТОРГ-2
- Excel акт
- переписка с менеджером
