buyer:
  code: berg_ru
  name: Berg
  enabled: true
  aliases:
    domains:
    - '@berg.ru'
    senders: []
    folders:
    - Возвраты Berru|berg.ru
    subject_contains:
    - возврат
    - претенз
    - рекламац
    body_contains:
    - возврат
    - брак
    - некондиц
statuses:
  quality_refusal:
  - отказ
processing_types:
  marking_request:
  - маркировк
fields:
  regex:
    document_number:
    - (?:УПД|счет|счёт|документ)\s*№?\s*([0-9]{4,})
    - (?:(?:УПД|накладн[аяой]+|документ[еу]?|счёт-фактур[аеу]?|заказ[еу]?|счёт|реализаци[яею]+)\s*(?:№|#)?\s*)\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{6,31})(?=[А-ЯЁа-яё])'
    part_number:
    - (?:артикул|каталожный|номер детали|part)\s*[:\s]*([A-Za-z0-9._\/-]{3,})
    - '[A-Za-z]+([A-Za-z0-9][A-Za-z0-9._/\-]{1,24})'
    document_date:
    - (?:(?:от|дата)\s+)\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})
    comment:
    - документам\s*:\s*([^\n\r]{4,160})
    - отказа\s*:\s*([^\n\r]{4,160})
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{19,44}?)
    - \d+\s*(брак\ \-\ Клиенту\ пришли\ б/у\ диски\ тормозные,\ ещё\ и\ с\ заказ\-нарядом\
      2025\ года)
    product_name:
    - (?:(?:деталь|наименовани[еяю]|номенклатур[аеу]|товар)[:\s\-]*)\s*([^\n\r]{3,80})
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{12,37}?)(?=[A-Za-z])'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{6,31}?)(?=[A-Za-z])
    - Автозапчасть\s*/\s*([^\n\r]{3,80})
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{33,58}?)(?=\d)'
    - ([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{29,54}?)(?=[А-ЯЁа-яё])
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{24,49}?)(?=\d)'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)(?=\d)
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)(?=\d)'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{17,42}?)'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{7,32}?)(?=\d)'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{10,35}?)(?=[A-Za-z])
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{18,43}?)'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[A-Za-z])
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{23,48}?)(?=[A-Za-z])'
    brand:
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})'
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{5,30})(?=[A-Za-z])'
    - '[A-Za-z]+([A-Za-z0-9][A-Za-z0-9._/\-]{6,31})(?=[А-ЯЁа-яё])'
required_documents:
- фото
