buyer:
  code: shate_m_ru
  name: Shate-M
  enabled: true
  aliases:
    domains:
    - '@shate-m.com'
    - '@shate-m.ru'
    senders: []
    folders:
    - Возвраты Berru|shate-m.com
    subject_contains:
    - возврат
    - претенз
    body_contains:
    - возврат
    - брак
fields:
  regex:
    document_number:
    - (?:УПД|счет|документ)\s*№?\s*([0-9]{4,})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=\d)'
    part_number:
    - (?:артикул|номер)\s*[:\s]*([A-Za-z0-9._\/-]{3,})
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{4,29})(?=[А-ЯЁа-яё])
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{2,27})(?=[A-Za-z])
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{7,32})(?=[А-ЯЁа-яё])
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,23})(?=[A-Za-z])
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])
    brand:
    - '[А-ЯЁа-яё]+\s*(FEBI\ BILSTEIN)(?=\d)'
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=\d)'
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[А-ЯЁа-яё])
    - '[А-ЯЁа-яё]+\s*(MAGNETI\ MARELLI)(?=\d)'
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{2,27})(?=\d)'
    document_date:
    - \d+\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})(?=\d)
    - \d+\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})(?=[A-Za-z])
    product_name:
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{30,55}?)(?=[A-Za-z])
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{14,39}?)(?=[A-Za-z])'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{21,46}?)(?=\d)'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{6,31}?)(?=[A-Za-z])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{15,40}?)(?=[A-Za-z])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[A-Za-z])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{8,33}?)(?=[A-Za-z])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{11,36}?)(?=[A-Za-z])
    comment:
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{16,41}?)(?=[А-ЯЁа-яё])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{4,29}?)(?=[А-ЯЁа-яё])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{1,25}?)(?=[А-ЯЁа-яё])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{12,37}?)(?=[А-ЯЁа-яё])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[А-ЯЁа-яё])
    claim_number:
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=\d)'
required_documents:
- фото
