buyer:
  code: trinity_parts_ru
  name: Trinity Parts
  enabled: true
  aliases:
    domains:
    - '@trinity-parts.ru'
    senders: []
    folders:
    - Возвраты Berru|trinity-parts.ru
    subject_contains:
    - возврат
    - претенз
    body_contains:
    - возврат
    - брак
fields:
  regex:
    document_number:
    - (?:УПД|счет|документ)\s*№?\s*([0-9]{4,})
    - накл\s*\.\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    - (?:(?:УПД|накладн[аяой]+|документ[еу]?|счёт-фактур[аеу]?|заказ[еу]?|счёт|реализаци[яею]+)\s*(?:№|#)?\s*)\s*([\dА-ЯA-Z][\w\-/\.]{0,30})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{6,31})(?=[А-ЯЁа-яё])'
    part_number:
    - (?:артикул|номер)\s*[:\s]*([A-Za-z0-9._\/-]{3,})
    - (?:(?:арт\.?|p/?n)\s*[:\-]?\s*)\s*([A-ZА-Я0-9][A-ZА-Яa-zA-Z0-9._\-/]{1,40})
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,24})
    brand:
    - SA046\s*,\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})(?=[A-Za-z])'
    - E410008\s*,\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - F722\s*,\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - 4113\s*,\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - GY2007G\s*,\s*([A-Za-z][A-Za-zА-Яа-я0-9\s\-]{0,30})
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,26})'
    - '[А-ЯЁа-яё]+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,25})(?=[A-Za-z])'
    comment:
    - возврат\s*,\s*([^\n\r]{4,160})
    - '[А-ЯЁа-яё]+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{10,35}?)(?=[А-ЯЁа-яё])'
    - УПД\s*\.\s*([^\n\r]{4,160})
    - \d+\s*(в\ отказе\ арт\.\ SA046)(?=[А-ЯЁа-яё])
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{10,35}?)(?=[А-ЯЁа-яё])
    product_name:
    - SANGSIN\s*,\s*([^\n\r]{3,80})
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{30,55}?)'
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{9,34}?)(?=[A-Za-z])
    - MILES\s*,\s*([^\n\r]{3,80})
    - BBC\s*,\s*([^\n\r]{3,80})
    - CTR\s*,\s*([^\n\r]{3,80})
    - \d+\s*([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{1,23}?)
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{23,48}?)(?=[A-Za-z])'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{29,54}?)(?=[А-ЯЁа-яё])'
    - '[A-Za-z]+([А-ЯЁа-яё][А-ЯЁа-яё\s\-\.]{13,38}?)(?=[А-ЯЁа-яё])'
    quantity:
    - \d+\s*([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})(?=[А-ЯЁа-яё])
    - ([A-Za-z0-9][A-Za-z0-9._/\-]{1,22})(?=\d)
    document_date:
    - клиента\s*:\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})
    - (?:(?:от|дата)\s+)\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})
    - отгрузку\s*:\s*(\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}-\d{2}-\d{2})
required_documents:
- фото
