buyer:
  code: avtoto_ru
  name: АВТОТО
  enabled: true
  aliases:
    domains:
    - '@avtoto.ru'
    senders:
    - k-rekl@avtoto.ru
    - post-rekl@avtoto.ru
    - return@avtoto.ru
    - nedovoz@avtoto.ru
    - order@avtoto.ru
    - noreplay@avtoto.ru
    folders: []
    subject_contains:
    - запрос на возврат
    - возврат
    - отказ
    - Заявка на передачу согласованных возвратов
    - Недопоставка
    - Рекламация №
    - А. ВОЗВРАТ
    - Поступил ответ по рекламации
    - Возврат проведен
    body_contains:
    - avtoto.ru
    - просим принять на возврат
    - personnel_claim
    - согласованными возвратами
    - снята в связи с нарушением срока поставки
    - Ознакомиться с рекламацией
    - недопоставка
statuses:
  quality_refusal:
  - отказ клиента
  - не подошло
  - не подошел
  - не подошёл
  - снята в связи с нарушением срока поставки заказа
  - верный подбор
  - деталь не подходит
  - отказ конечного покупателя
  wrong_item:
  - ошибочный кросс
  - пересорт
  - не тот артикул
  - пришла запчасть со второго поколения вместо третьего
  - вместо третьего
  - пересортица
  defect:
  - брак
  - дефект
  nonconforming:
  - некондиция
  - пакет вскрыт
  - упаковка вскрыта
  - неконд
  - некондиционный товар
  - без маркировки/тары
  - без маркировки
  shortage:
  - недопоставка
  - недовоз
processing_types:
  external_claim_link:
  - personnel_claim
  - avtoto.ru/personnel_claim
  - nondelivery
  - avtoto.ru/nondelivery
  new_return:
  - просим принять на возврат
  - рассмотреть возможность возврата
  follow_up_request:
  - возврат проведен
  - просим одобрить возврат
  - просьба дать ответ
  - поступил ответ по рекламации
  - ожидаем ответ
  - ждем ответ
  - ждём ответ
  - ожидаем согласование
  - ждем согласование
  - возврат согласован
  - почему не отвечаете
  - ждем согласование возврата
  - просим согласовать возврат
  - ожидаем согласование возврата
  - повтор
  evidence_request:
  - предоставить видео
  - видео приемки
  - видео приёмки
  - фото неинформативны
  return_ready_notification:
  - согласованными возвратами
  - передача согласованных возвратов
  - подошел за согласованными возвратами
  - согласованные возвраты
  - заявка на передачу согласованных возвратов
  pre_delivery_cancellation:
  - снята в связи с нарушением срока поставки заказа
required_documents:
- фото
- ТОРГ-12 / возвратная накладная
field_extractors: []
